// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iluwflkoouqzucotzroq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsdXdmbGtvb3VxenVjb3R6cm9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjcwMTUsImV4cCI6MjA2ODk0MzAxNX0.ljttWUZ7T7Wq9mO31mTd01X-Y-3uM265jB_DQqj9j1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});